package fr.osallek.eu4parser.model.save.counters;

public enum Counter {
    SIEGE, MONARCH, LEADER, ADVISOR, REBEL_FACTION, DIPLOMACY_ACTION, CARDINAL, MERCENARY_COMPANY, NOT_FOUND_9, ARMY, REGIMENT, NOT_FOUND_12
}
