package com.osallek.eu4parser.model.empire;

public enum DecreeType {
    EXPAND_BUREAUCRACY_DECREE,
    CONDUCT_CENSUS_DECREE,
    PROMOTE_NAVAL_OFFICERS_DECREE,
    INCREASE_TARIFF_CONTROL_DECREE,
    IMPROVE_DEFENCE_EFFORT_DECREE,
    BOOST_OFFICER_CORPS_DECREE
}
