package fr.osallek.eu4parser.model.save.war;

public enum WarGoalType {
    TAKE_COLONY, TAKE_CORE, TAKE_BORDER, TAKE_PROVINCE, TAKE_CAPITAL, DEFEND_CAPITAL, DEFEND_COUNTRY, NAVAL_SUPERIORITY, SUPERIORITY, TAKE_REGION,
    BLOCKADE_PORTS
}
