package com.osallek.eu4parser.model.country;

public enum AgeAbility {
    AB_ALLOW_FEUDAL_DE_JURE_LAW, AB_JUSTIFIED_WARS, AB_TRANSFER_VASSAL_WARGOAL, AB_FREE_WAR_TAXES, AB_CAVALRY_ARMIES,
    AB_COLONY_BOOST_DEVELOPMENT, AB_ATTACK_BONUS_IN_CAPITAL_TERRAIN, AB_OTTOMAN_SIEGE_ABILITY, AB_PORTUGAL_COLONIAL_GROWTH,
    AB_DENMARK_REDUCED_LIB_DESIRE, AB_VENICE_SHIP_TRADE, AB_ALLOW_RELIGION_ENFORCED, AB_SIEGE_BLOCKADES,
    AB_WARSCORE_VS_RELIGION, AB_MERCENARY_DISCIPLINE, AB_SHIP_POWER_PROPAGATION, AB_INSTITUTION_SPREAD_FROM_TRUE_FAITH,
    AB_PRESTIGE_PER_DEVELOPMENT_FROM_CONVERSION, AB_SPAIN_TERCIO, AB_MUGHAL_ARTILLERY, AB_POLISH_LEGITIMACY,
    AB_PERSIA_REINFORCE, AB_ALLOW_EDICT_OF_ABSOLUTISM, AB_RIVAL_CHANGE, AB_RIVAL_BORDER_FORT, AB_AUTONOMY,
    AB_HARSH_TREATMENT, AB_ADM_EFFICIENCY, AB_YEARLY_ABSOLUTISM, AB_FRANCE_FIRE_DAMAGE, AB_DUTCH_ANTI_CORRUPTION,
    AB_SWEDEN_MANPOWER, AB_MANCHU_BANNER, AB_ALLOW_ANTI_REVOLUTIONARY_ZEAL, AB_NAPOLEONIC_WARFARE, AB_FORCE_MARCH,
    AB_MORE_SHIPS_CAN_FIRE, AB_NO_DISTANCE_FOR_CORE, AB_BACKROW_ARTILLERY, AB_SAME_CONTINE_LIB_DESIRE, AB_PRU_MILITARY,
    AB_GBR_FLEET, AB_RUSSIA_BOOST, AB_AUSTRIA_REP
}
